apply plugin: 'java'

ext {
    isDev = false
}

sourceCompatibility = 11
targetCompatibility = 11

repositories {
    mavenLocal()

    if (isDev) {
        maven {
            url 'http://dev-registry.portswigger.com/repository/maven-public'
        }
    }
    else {
        mavenCentral()
    }
}

dependencies {
    compileOnly 'net.portswigger.burp.extensions:montoya-api:2025.12'
    implementation 'com.google.code.gson:gson:2.8.5'
}

jar {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
